# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.

# JupyterHub docker-compose configuration file
version: "3.6"

services:
  nginx-proxy:
    labels:
      "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy": "true"
    image: jwilder/nginx-proxy:${NGINX_PROXY_VERSION}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "vhost:/etc/nginx/vhost.d"
      - "html:/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      - "certs:/etc/nginx/certs"
    restart: always
    env_file:
      - .config/nginx

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion:${PROXY_COMPANION_VERSION}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "vhost:/etc/nginx/vhost.d"
      - "html:/usr/share/nginx/html"
      - "certs:/etc/nginx/certs"
    restart: always

  mmt-server:
    image: kwarc/mmt:${MMT_VERSION}
    container_name: mmt-server
    restart: always
    command: ["-w", "--file=/content/MathHub/meta/inf/mathhub.msl"]
    environment:
      VIRTUAL_PORT: 9000
    env_file:
      - .config/mmt
      - .config/mmt-archives
    volumes:
      - "mmtdata:/content"

  hub-db:
    image: postgres:9.5
    container_name: jupyterhub-db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${DB_VOLUME_CONTAINER}
    env_file:
      - .config/postgres
    volumes:
      - "db:${DB_VOLUME_CONTAINER}"

  hub:
    image: mathhub/jupyter
    depends_on:
      - hub-db
    restart: always
    container_name: jupyterhub
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
      - "data:${DATA_VOLUME_CONTAINER}"
    ports:
      - "80"

    environment:
      MMT_BASE_URL: "http://mmt-server:9000"
      MMT_VOLUME_HOST: ${MMT_VOLUME_HOST}
      VIRTUAL_PORT: 80

      DOCKER_NETWORK_NAME: ${DOCKER_NETWORK_NAME}

      DOCKER_NOTEBOOK_IMAGE_MMT: ${LOCAL_NOTEBOOK_IMAGE_MMT}
      DOCKER_NOTEBOOK_IMAGE_INTERVIEW: ${LOCAL_NOTEBOOK_IMAGE_INTERVIEW}

      DOCKER_NOTEBOOK_DIR: ${DOCKER_NOTEBOOK_DIR}
      DOCKER_SPAWN_CMD: ${DOCKER_SPAWN_CMD}

      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: hub-db

    env_file:
      - .config/postgres
      - .config/jupyterhub
    command: >
      jupyterhub -f /srv/jupyterhub/jupyterhub_config.py

volumes:
  data:
    external:
      name: ${DATA_VOLUME_HOST}
  db:
    external:
      name: ${DB_VOLUME_HOST}
  mmtdata:
    external:
      name: ${MMT_VOLUME_HOST}
  portainer:
  vhost:
  html:
  certs:

networks:
  default:
    external:
      name: ${DOCKER_NETWORK_NAME}
